name: Build-DEV

on:
  push:
    tags:
      - "*"
    branches:
      - "dev*"
      - "feature*"
      - "beta*"
  workflow_dispatch:

jobs:
  variables:
    name: Assign variables
    outputs:
      sem_ver: ${{ steps.var.outputs.sem_ver }}
    runs-on: "ubuntu-latest"
    steps:
      - name: Split branch name
        id: split
        run: echo "fragment=${${{ github.ref_name }}%%/*}" >> $GITHUB_OUTPUT

      - name: Setting global variables
        uses: actions/github-script@v7
        id: var
        with:
          script: |
            core.setOutput('sem_ver', '${{ github.ref_name }}'.replaceAll('\/', '-'))

  windows_build:
    name: Build and Zip
    needs: [variables]
    runs-on: windows-latest

    defaults:
      run:
        shell: powershell

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
          architecture: "x86"
          cache: 'pip' # caching pip dependencies

      - name: Install python requirements
        run: |
          pip install -r requirements.txt

      - name: Build runED
        run: |
          pyinstaller main.py --name runED --icon img\runED.ico --workpath build --contents-directory . --distpath .\dist --clean

      - name: Add files to dist
        run: |
          $files = ( 'CHANGELOG.md', 'README.md', 'UNLICENSE' ); foreach ( $file in $files ) { Copy-Item -Path $file -Destination '.\dist\runED\' }

      - name: Zip it
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          path: './dist/runED/'
          filename: 'runED/runED-${{ needs.variables.outputs.sem_ver }}.zip'

      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: built-files-windows
          path: |
              runED\runED-*.zip
